# Generated by Django 5.2.17 on 2026-10-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistente',
            name='extension',
            field=models.CharField(blank=True, max_length=6, verbose_name='extensión'),
        ),
    ]
